---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: agents
  labels:
    istio-injection: enabled
